"""initial

Revision ID: 8bb3e681572d
Revises: 
Create Date: 2024-06-30 12:41:53.588345

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8bb3e681572d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spimex_trading_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exchange_product_id", sa.String(), nullable=True),
        sa.Column("exchange_product_name", sa.String(), nullable=True),
        sa.Column("oil_id", sa.String(), nullable=True),
        sa.Column("delivery_basis_id", sa.String(), nullable=True),
        sa.Column("delivery_basis_name", sa.String(), nullable=True),
        sa.Column("delivery_type_id", sa.String(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("total", sa.Float(), nullable=True),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_spimex_trading_results_exchange_product_id"),
        "spimex_trading_results",
        ["exchange_product_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_spimex_trading_results_exchange_product_id"),
        table_name="spimex_trading_results",
    )
    op.drop_table("spimex_trading_results")
    # ### end Alembic commands ###
